# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless-template
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

plugins:
  - serverless-offline

functions:
  application:
    handler: dist/serverlessHandler.api
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

